# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2017

# Custom your favicon.ico in `site/source`
favicon: /mylog.png

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  Categories: /categories/
  About: /about

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  toc: true
  fancybox: true
  pjax: true

copyright:
  enable: true
  # https://creativecommons.org/
  license: '<a rel="license" href="http://creativecommons.org/licenses/by-nc/4.0/" target="_blank">知识共享署名-非商业性使用 4.0 国际许可协议-转载请注明出处！</a>'

reward:
  enable: false
  qrCode:
    wechat:
    alipay:

# ===========================================
# Social links Settings
# ===========================================
social:
  email: hadronw@qq.com
  stack-overflow:
  twitter:
  facebook:
  linkedin:
  google:
  github: https://github.com/hadronw
  weibo:
  zhihu:
  douban:
  pocket:
  tumblr:
  instagram:

# ===========================================
# Third Party Services Settings
# ===========================================

# LeanCloud
leancloud:
  app_id: q4mf6h8NnS0MNjTqEsBsKusw-gzGzoHsz
  app_key: 7oNyN2nBpEXdSt04snJIsgPn

# Baidu Analytics
baidu_analytics: 80d9b9996150c7cdf8ba27fb6575a66f

# Google Analytics
google_analytics: UA-113179601-1

# ===========================================
# Third Party Services Settings ——Verification
# 修改文件/even/layout/_/partial/_head/meta.swing
# ===========================================


# Google Verification
google_verification: cXrmNsZjDqC3drL1XY6-CZURO2H7s8X-njVT3_EFO8s

# Baidu Verification
baidu_verification: jUV4JeBMWP

# Sogou Verification
sogou_verification: 30h62eUCDR

# ===========================================
# Third Party Services Settings —— comments
# ===========================================


# Disqus key: (authenticated)
disqus_shortname: 

#Changyan
changyan:
  appid:
  appkey:

#LiveRe 来必力 MTAyMC8zNjg0MS8xMzM3Nw
livere_datauid: MTAyMC8zNjg0MS8xMzM3Nw

# ===========================================
# Version
# ===========================================
version: 2.8.0
